### ISSUE TITLE
Dataset dowload failure

### ISSUE THREAD

**Issue by yoav-tal** [lixx2938/MegaDepth#20]
Hi
I tried to download the dataset (the 199GB one). It failed in two attempts on different devices and operation system - is it possible that something's wrong at your end?
Thanks!

**Comment by OwenHua666** [comment]
Did you figure out how to download the dataset?

**Comment by yoav-tal** [comment]
The problem I presented in my query then turned out to be internal.
Nevertheless getting the data was cumbersome and I had to involve a DevOps
expert. Not that it is necessary for anyone to so, but I didn't have time
to handle it myself.

בתאריך יום ו׳, 3 במאי 2019, 20:07, מאת OwenJoy ‏<notifications@github.com>:

**Comment by OwenHua666** [comment]
Thank u for your immediate response. I have tried my best to get this dataset but failed. Do you by chance still have this dataset somewhere so I can download from your copy?

Best regards,

Owen

On Fri, May 3, 2019 at 11:22 Yoav Tal <notifications@github.com<mailto:notifications@github.com>> wrote:
The problem I presented in my query then turned out to be internal.
Nevertheless getting the data was cumbersome and I had to involve a DevOps
expert. Not that it is necessary for anyone to so, but I didn't have time
to handle it myself.

בתאריך יום ו׳, 3 במאי 2019, 20:07, מאת OwenJoy ‏<notifications@github.com<mailto:notifications@github.com>>:
